import type { Metadata } from "next";
import { Inter as FontSans } from "next/font/google";
import Sidebar from "@/components/Sidebar";

const fontSans = FontSans({
	subsets: ["latin"],
	variable: "--font-sans",
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<div className="min-h-screen flex w-full">
			<div className="w-64 bg-slate-800 h-full min-h-screen inset-y-0">
				<Sidebar />
			</div>
			<div className="flex flex-1 bg-slate-50 justify-center w-full">
				{children}
			</div>
		</div>
	);
}
